Repository hmterestingthinking/Honeybread, pull requests merged in 2021-03, with the labels that each got.

#2 [COMMON] Swagger 설정
  honeybread-channel/src/main/java/com/whatsub/honeybread/channel/config/ChannelSwaggerConfig.java
  honeybread-channel/src/main/java/com/whatsub/honeybread/channel/support/ChannelSwaggerTags.java
  honeybread-common/src/main/java/com/whatsub/honeybread/common/api/TestController.java
  honeybread-common/src/main/java/com/whatsub/honeybread/common/config/SwaggerConfig.java
  honeybread-common/src/main/java/com/whatsub/honeybread/common/support/HoneyBreadSwaggerTags.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/config/MgmtAdminSwaggerConfig.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/support/MgmtAdminSwaggerTags.java
Labels: PR, 이슈, 코드리뷰

#8 [DEVELOP] 카테고리 등록 기능
  honeybread-core/src/main/java/com/whatsub/honeybread/core/infra/errors/ErrorCode.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/category/CategoryController.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/category/CategoryRequest.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/category/CategoryService.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/category/CategoryControllerTest.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/category/CategoryServiceTest.java
Labels: 코드리뷰

#9 [COMMON] Swagger / QuerydslRepositorySupport
  honeybread-common/src/main/java/com/whatsub/honeybread/common/config/SwaggerConfig.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/infra/errors/ErrorResponse.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/infra/exception/HoneyBreadException.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/support/QuerydslRepositorySupport.java
Labels: PR, 이슈

#10 [DEVELOP] 카테고리 기능
  honeybread-common/src/main/java/com/whatsub/honeybread/common/config/SwaggerConfig.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/config/JpaConfig.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/base/BaseEntity.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/category/Category.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/category/CategoryRepository.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/category/CategoryRepositoryCustom.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/category/CategoryRepositoryImpl.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/category/dto/CategorySearch.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/infra/errors/ErrorCode.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/infra/errors/ErrorResponse.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/infra/exception/HoneyBreadException.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/support/QuerydslRepositorySupport.java
  honeybread-core/src/test/java/com/whatsub/honeybread/core/domain/category/CategoryRepositoryTest.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/category/CategoryController.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/category/CategoryQueryService.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/category/CategoryService.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/category/dto/CategoryRequest.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/category/dto/CategoryResponse.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/category/CategoryControllerTest.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/category/CategoryQueryServiceTest.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/category/CategoryServiceTest.java
Labels: PR, 코드리뷰

#11 [ Develop ] 유저 스토어 찜 등록 기능
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/Store.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/StoreRepository.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/userstorefavorite/UserStoreFavorite.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/userstorefavorite/UserStoreFavoriteRepository.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/infra/errors/ErrorCode.java
  honeybread-core/src/test/java/com/whatsub/honeybread/core/domain/userstorefavorite/UserStoreFavoriteRepositoryTest.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/config/MgmtAdminMvcConfig.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/userstorefavorite/ChannelUserSession.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/userstorefavorite/UserStoreFavoriteController.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/userstorefavorite/UserStoreFavoriteService.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/support/MgmtAdminSwaggerTags.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/userstorefavorite/UserStoreFavoriteControllerTest.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/userstorefavorite/UserStoreFavoriteServiceTest.java
Labels: PR, 코드리뷰

#16 [Develop] 유저 기능
  honeybread-core/src/main/java/com/whatsub/honeybread/core/config/SecurityConfig.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/user/User.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/user/UserRepository.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/infra/errors/ErrorCode.java
  honeybread-core/src/test/java/com/whatsub/honeybread/core/domain/user/UserRepositoryTest.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/user/UserController.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/user/UserService.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/user/dto/UserModifyRequest.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/user/dto/UserRequest.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/user/dto/UserResponse.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/support/MgmtAdminSwaggerTags.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/user/UserControllerTest.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/user/UserServiceTest.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/user/dto/UserRequestTest.java
  pom.xml
Labels: PR, 코드리뷰

#17 [ REFACTOR ] 카테고리 기능
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/category/CategoryQueryService.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/category/CategoryControllerTest.java
Labels: PR

#18 [Refactor] User관련 ErrorCode 수정 및 테스트 추가
  honeybread-core/src/main/java/com/whatsub/honeybread/core/infra/errors/ErrorCode.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/user/UserControllerTest.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/user/UserServiceTest.java
Labels: PR

#14 [ Develop ] 찜 삭제/ 찜한 스토어 목록 조회
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/Store.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/dto/StoreIdsResponse.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/userstorefavorite/UserStoreFavoriteRepository.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/infra/errors/ErrorCode.java
  honeybread-core/src/test/java/com/whatsub/honeybread/core/domain/userstorefavorite/UserStoreFavoriteRepositoryTest.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/userstorefavorite/UserStoreFavoriteController.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/userstorefavorite/UserStoreFavoriteQueryService.java
  honeybread-mgmtadmin/src/main/java/com/whatsub/honeybread/mgmtadmin/domain/userstorefavorite/UserStoreFavoriteService.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/userstorefavorite/UserStoreFavoriteControllerTest.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/userstorefavorite/UserStoreFavoriteQueryServiceTest.java
  honeybread-mgmtadmin/src/test/java/com/whatsub/honeybread/mgmtadmin/domain/userstorefavorite/UserStoreFavoriteServiceTest.java
Labels: PR

#21 [ Develop ] 스토어 엔티티 설계
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/Address.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/BankAccount.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/BankType.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/BusinessHours.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/BusinessLicense.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/OperationStatus.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/PayType.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/Store.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/StoreAnnouncement.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/StoreBasic.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/StoreCategory.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/StoreOperation.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/StorePayMethod.java
  honeybread-core/src/main/java/com/whatsub/honeybread/core/domain/store/StoreStatus.java
Labels: PR
